const StepOneData = {
  titles: [
    {text: '先生', value: 'mr'},
    {text: '女士', value: 'ms'},
    {text: '不明', value: 'mx'},
  ],
  cities: [
    {text: '請選擇縣市', value: ''},
    {text: '基隆市', value: 'KLU'},
    {text: '新北市', value: 'TPH'},
    {text: '臺北市', value: 'TPE'},
    {text: '桃園市', value: 'TYC'},
    {text: '新竹縣', value: 'HSH'},
    {text: '新竹市', value: 'HSC'},
    {text: '苗栗市', value: 'MAC'},
    {text: '苗栗縣', value: 'MAL'},
    {text: '臺中市', value: 'TXG'},
    {text: '彰化縣', value: 'CWH'},
    {text: '彰化市', value: 'CWS'},
    {text: '南投市', value: 'NTC'},
    {text: '南投縣', value: 'NTO'},
    {text: '雲林縣', value: 'YLH'},
    {text: '嘉義縣', value: 'CHY'},
    {text: '嘉義市', value: 'CYI'},
    {text: '臺南市', value: 'TNN'},
    {text: '高雄市', value: 'KHH'},
    {text: '屏東縣', value: 'IUH'},
    {text: '屏東市', value: 'PTS'},
    {text: '宜蘭縣', value: 'ILN'},
    {text: '宜蘭市', value: 'ILC'},
    {text: '花蓮縣', value: 'HWA'},
    {text: '花蓮市', value: 'HWC'},
    {text: '臺東市', value: 'TTC'},
    {text: '臺東縣', value: 'TTT'},
    {text: '澎湖縣', value: 'PEH'},
    {text: '金門縣', value: 'KMN'},
    {text: '連江縣', value: 'LNN'},
  ],
}

export default StepOneData;